service: task-backend

provider:
  name: aws
  runtime: python3.9  # Use Python 3.9 runtime
  region: us-east-1   # Change to your preferred AWS region

functions:
  app:
    handler: main.handler  # This points to the `handler` in main.py
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true  # Ensures compatibility with Lambda's environment