version: "3.8"

services:
    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        environment:
            - DATABASE_NAME=task_management_dev

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
